### ISSUE TITLE
Not working on windows 10

### ISSUE THREAD

**Issue by Ornias1993** [remcohaszing/pywakeonlan#2]
The script (and underlaying program) doesn't seem to be working on windows 10, any info on that?

It does detect wrong entered MAC details, but after execution the PC doesn't start.

It doesn't seem to be a local problem, other WOL utility's seem to work fine.
Also it doesn't seem to be a script problem, running the program using other utility's (ex. home assistant) doesn't seem to work either.

**Comment by vtestagrossa** [comment]
In Windows 10, the socket libraries prevent sending broadcast to 255.255.255.255 via UDP in Python for some reason. Use the wol.send_magic_packet('ff.ff.ff.ff.ff.ff', ip_address='192.168.1.255', port=9) but obviously substitute the values for the mac address, the first 3 octets of your LAN (you can even send using a class A broadcast in Windows 10, but not all 4 octets), and the destination port. It's working for me when I use it like that.

**Comment by remcohaszing** [comment]
I never tested this on Windows. I'm going to assume the comment by @vtestagrossa resolves this issue. If not, please leave a comment (and a PR if possible 😄 ).
