### ISSUE TITLE
Permissions issue on Raspberry Pi OS

### ISSUE THREAD

**Issue by Lax4ever** [remcohaszing/pywakeonlan#20]
Trying to utilize a Raspberry Pi 4 as a wake on lan hub for other devices on my network. The following script works via Windows and via Ubuntu Server 18.04 but not via Raspian Buster.

```
from wakeonlan import send_magic_packet;

def wakeup():
    send_magic_packet('_MAC_', ip_address='_subnet_.255', port=9)

if __name__ == "__main__":
    wakeup()
```

When used on Raspbian, a permissions error occurs:

```
Traceback (most recent call last):
  File "foo.py", line 7, in <module>
    wakeup()
  File "foo.py", line 4, in wakeup
    send_magic_packet('_MAC_', ip_address='_subnet_.255', port=9)
  File "/usr/local/lib/python3.7/dist-packages/wakeonlan.py", line 58, in send_magic_packet
    sock.send(packet)
PermissionError: [Errno 1] Operation not permitted
```
As you can see this is running via Python 3, I have tried running the script with `sudo` with the same results. Running it through an elevated Python 3 shell produces no error but also no result.

I am not sure how to resolve since it works on Ubuntu Server and Windows. Any advice would be appreciated.

**Comment by ericfrey** [comment]
On a raspberry pi running Raspbian 10 wakeonlan works for me if the user is a member of the netdev group.

**Comment by remcohaszing** [comment]
@Lax4ever does that answer your question?

**Comment by remcohaszing** [comment]
I’m closing this issue, as it’s not actionable for this repository.
