### ISSUE TITLE
No module named 'wakeonlan'

### ISSUE THREAD

**Issue by PearTV** [remcohaszing/pywakeonlan#32]
My issue is simple:
I'm trying to run some code I wrote in python with flask.

When I run it, it gives me the following error:
_ModuleNotFoundError: No module named 'wakeonlan'_

Now you might be thinking I just forgot to install wakeonlan, but that's the thing: I didn't. wakeonlan is installed and running _wakeonlan --version_ does result in it telling me what version of wakeonlan have installed.

I'm running this on a raspberry pi 4 using Raspberry Pi OS 64bit if that makes any difference.

I'm new to python, flask, linux and pi so I'msorry if this is a real easy fix. I am noob.

**Comment by remcohaszing** [comment]
Don’t call yourself a noob. Everyone has to start somewhere, but _noob_ has a negative ring to it. :)

You probably have multiple Python environments. The `wakeonlan` executable on in your `$PATH` is uses a different environment than the `python` executable in your `$PATH`. While Python environments are a flexible and powerful feature, many people find it confusing.

I can’t really help with this, as it’s very specific to your setup. You can start by running `which python` and `which wakeonlan`, and checking where the first line of `wakeonlan` points to.
