### ISSUE TITLE
from mock

### ISSUE THREAD

**Issue by SwiperToYou** [remcohaszing/pywakeonlan#5]
Beginner programmer here.This is such a great code! I am having one issue and I am not sure why it started happening. Once I ran the set up and started the test_wakeonlan it would stop at mock. 

So originally when I got the code to run just running running setup and creating a pytest.py file. It stopped on me all of the sudden not sure why. Any Ideas or certain order I am supposed to run this? Again I am a beginner starting with python I understand it but I do not know how to write many programs.

Thanks!

**Comment by remcohaszing** [comment]
Hi @SwiperToYou,

It's cool you're starting to program, however, GitHub is no the right place to ask such basic programming questions.

This project uses tox and virtualenv to create environments for testing. The `mock` package is installed in these virtualenvs.

If you want to learn Python properly, I recommend taking a look at these tools:

- [pip](https://pip.pypa.io/en/stable/)
- [virtualenv](https://virtualenv.pypa.io/en/stable/)
- [virtualenvwrapper](https://virtualenvwrapper.readthedocs.io/en/latest/) (Only for Linux / OS X)
- [tox](https://tox.readthedocs.io/en/latest/)
