### ISSUE TITLE
Push a new version to pypi

### ISSUE THREAD

**Issue by Tadly** [remcohaszing/pywakeonlan#7]
106af61fe0fcce9b524fd86ce6bdac4db5cc1e6e is quite a sever issue causing some of my devices to not react to magic packets as they reject invalid formats.

As big projects such as [home-assistant](https://github.com/home-assistant/home-assistant) depend on it, I'd really appreciate a new version being pushed to pypi.

**Comment by remcohaszing** [comment]
I should have done this a long time ago… anyway, done :white_check_mark:  :smile:
